[package]
name = "vecs_cli"
version = "0.1.0"
edition.workspace = true

[dependencies]
bumpalo = { workspace = true, features = ["collections"] }
clap = { version = "4.5.47", features = ["derive"] }

[dev-dependencies]
derive_builder = "0.20.2"
