[package]
name = "vecs_cli"
version = "0.1.0"
edition.workspace = true

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
regex = "1.12.2"

[dev-dependencies]
derive_builder = "0.20.2"
