[workspace]
resolver = "3"
members = ["vecs_cli"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
bumpalo = { version = "3.19.0" }

[profile.dev]
panic = "abort"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"
