[workspace]
resolver = "3"
members = ["vecs_cli"]

[workspace.package]
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"
